version: '3'
services:
  langchain-frontend:
    image: notlangchain/langchainplus-frontend:latest
    ports:
      - 4173:4173
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend
    restart: unless-stopped
  langchain-backend:
    image: notlangchain/langchainplus:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - 8000:8000  # somehow langchain.js is calling port 1984 instead of 8000
    depends_on:
      - langchain-db
    restart: unless-stopped
  langchain-db:
    image: postgres:14.1
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    restart: unless-stopped
  proxy:
    build: .
    ports:
      - "1984:1984"
    environment:
      - TARGET=http://langchain-backend:8000
      - OS_HOST=http://host.docker.internal:9200
      - OS_USER=
      - OS_PASS=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
